In [17]:
from tensorflow.keras import Sequential,layers

network = Sequential([ # 网络容器
    layers.Conv2D(6,kernel_size=3,strides=1), # 第一个卷积层, 6个3x3卷积核 
    layers.MaxPooling2D(pool_size=2,strides=2), # 高宽各减半的池化层
    layers.ReLU(), # 激活函数
    layers.Conv2D(16,kernel_size=3,strides=1), # 第二个卷积层, 16个3x3卷积核
    layers.MaxPooling2D(pool_size=2,strides=2), # 高宽各减半的池化层 
    layers.ReLU(), # 激活函数
    layers.Flatten(), # 打平层，方便全连接层处理
    layers.Dense(120, activation='relu'), # 全连接层，120个节点
    layers.Dense(84, activation='relu'), # 全连接层，84节点 
    layers.Dense(10) # 全连接层，10个节点
])
network.build(input_shape=(4,28,28,1))
# 统计网络信息
network.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            multiple                  60        
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 multiple                  0         
_________________________________________________________________
re_lu_6 (ReLU)               multiple                  0         
_________________________________________________________________
conv2d_7 (Conv2D)            multiple                  880       
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 multiple                  0         
_________________________________________________________________
re_lu_7 (ReLU)               multiple                  0         
_________________________________________________________________
flatten_3 (Flatten)          multiple                 

In [7]:
import tensorflow as tf
x =tf.random.uniform([2,2,3], maxval=10, dtype=tf.int32)
x

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[9, 7, 4],
        [7, 1, 7]],

       [[4, 8, 5],
        [5, 9, 2]]], dtype=int32)>

In [8]:

tf.expand_dims(x,0)

<tf.Tensor: shape=(1, 2, 2, 3), dtype=int32, numpy=
array([[[[9, 7, 4],
         [7, 1, 7]],

        [[4, 8, 5],
         [5, 9, 2]]]], dtype=int32)>