In [8]:
import tensorflow as tf
import numpy as np
a =np.array([[1,2],
         [3,4]])
tf.convert_to_tensor(a)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

In [44]:
from tensorflow.keras import layers, optimizers, datasets # 导入 TF 子库

In [40]:
import keras
(x_train,y_train),(x_test,y_test)=keras.datasets.imdb.load_data(num_words=1000)
x_train.shape
x_train[:100]

array([list([1, 14, 22, 16, 43, 530, 973, 2, 2, 65, 458, 2, 66, 2, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 2, 2, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2, 19, 14, 22, 4, 2, 2, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 2, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2, 2, 16, 480, 66, 2, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 2, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 2, 15, 256, 4, 2, 7, 2, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 2, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2, 56, 26, 141, 6, 194, 2, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 2, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 2, 88, 12, 16, 283, 5, 16, 2, 113, 103, 32, 15, 16, 2, 19, 178, 32]),
       list([1, 194, 2, 194, 2, 78, 228, 5, 6, 2, 2, 2, 134, 26, 4, 715, 8, 118, 2, 14, 394, 20, 13, 119, 954, 189,

In [93]:
x =tf.random.normal([2,2,2,3])  # 4张图片
x

<tf.Tensor: shape=(2, 2, 2, 3), dtype=float32, numpy=
array([[[[-0.07922164, -2.5001698 ,  0.38743445],
         [ 1.0483831 , -2.270541  ,  0.3459003 ]],

        [[ 1.081175  , -0.74933547, -0.25429097],
         [-0.06790902,  0.6780439 , -1.5232481 ]]],


       [[[ 0.610809  ,  0.00577707, -0.42530796],
         [ 0.0606464 ,  1.1246043 ,  0.31658423]],

        [[-0.7192619 , -0.21857218, -0.8217806 ],
         [-0.48216212,  0.92925036, -1.0163995 ]]]], dtype=float32)>

In [112]:
x[0,0,0,:]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.07922164, -2.5001698 ,  0.38743445], dtype=float32)>

In [170]:
x =tf.random.uniform([1,3], maxval=10, dtype=tf.int32)
x

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[8, 1, 3]], dtype=int32)>

In [261]:
x=tf.random.normal([4,10])
x

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[ 0.08943908, -1.1907333 , -0.43190542,  0.03853942, -0.5761931 ,
        -1.1927643 ,  0.5950316 , -1.5779927 ,  0.5572929 , -0.19758505],
       [ 0.4727491 ,  0.33135027,  1.2671785 , -1.4572622 ,  0.70421976,
        -0.38538212,  1.0340242 , -0.88383615,  0.45394406, -0.72167355],
       [ 0.6461572 ,  0.40390572,  0.11512091,  0.73199713,  1.05473   ,
         0.4846252 , -0.545639  ,  0.16937605, -0.10775869,  0.50865674],
       [ 1.3815963 , -0.62004113, -0.1000035 ,  1.9219803 ,  0.04310442,
        -2.0668838 ,  0.12619951,  1.6292353 ,  0.92748547, -0.24240759]],
      dtype=float32)>

In [262]:
print(tf.reduce_max(x,axis=1))
print(tf.reduce_min(x, axis=1))
print(tf.reduce_mean(x,axis=1))
print(tf.reduce_mean(x))

tf.Tensor([0.5950316 1.2671785 1.05473   1.9219803], shape=(4,), dtype=float32)
tf.Tensor([-1.5779927 -1.4572622 -0.545639  -2.0668838], shape=(4,), dtype=float32)
tf.Tensor([-0.38868707  0.08153119  0.3461171   0.30002654], shape=(4,), dtype=float32)
tf.Tensor(0.08474696, shape=(), dtype=float32)


In [286]:
out = tf.random.normal([100,10])
out=tf.nn.softmax(out, axis=1)
pred= tf.argmax(out, axis=1)
pred

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([8, 2, 8, 3, 1, 3, 1, 0, 8, 7, 4, 6, 7, 4, 0, 4, 1, 7, 3, 3, 2, 8,
       4, 9, 2, 8, 5, 7, 1, 2, 6, 9, 0, 2, 3, 9, 6, 1, 2, 3, 0, 5, 5, 2,
       7, 7, 5, 2, 9, 6, 1, 1, 4, 9, 0, 1, 9, 6, 1, 0, 5, 6, 4, 2, 4, 1,
       1, 4, 6, 3, 0, 0, 5, 9, 9, 9, 2, 3, 6, 8, 5, 7, 5, 8, 2, 8, 0, 6,
       6, 6, 6, 1, 5, 5, 1, 1, 8, 7, 5, 4])>

In [288]:
# 模拟真实标签
y=tf.random.uniform([100], dtype=tf.int64, maxval=10)
y

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([3, 4, 4, 2, 0, 3, 9, 2, 0, 3, 4, 9, 1, 4, 3, 4, 1, 2, 3, 4, 3, 3,
       7, 9, 7, 4, 7, 1, 9, 1, 8, 3, 5, 3, 5, 3, 8, 7, 1, 3, 6, 5, 1, 4,
       0, 2, 1, 5, 2, 3, 7, 6, 4, 8, 9, 7, 0, 3, 5, 6, 4, 9, 5, 0, 1, 7,
       9, 7, 0, 7, 6, 3, 0, 6, 4, 7, 7, 5, 3, 9, 9, 6, 5, 6, 0, 3, 5, 2,
       2, 7, 3, 4, 1, 4, 5, 7, 5, 8, 1, 4])>

In [296]:
out= tf.equal(pred,y)
out
out=tf.cast(out, dtype=tf.float32)
print(out)
tf.reduce_sum(out)

tf.Tensor(
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1.], shape=(100,), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [299]:

b=tf.random.normal([4,2,2,3])
print(b)
c =tf.tile(b,[2,3,3,1])

tf.Tensor(
[[[[-1.42396    -0.45054424 -0.47255576]
   [ 0.68828875  1.0822066  -0.30823535]]

  [[ 2.06897     0.773548    0.0609053 ]
   [-0.54088354  1.4164207   0.91411054]]]


 [[[ 2.6259074   0.23563538 -0.6199665 ]
   [ 0.6613539  -0.9630761   0.5333628 ]]

  [[-1.3439453   1.1207529   0.16851386]
   [-0.82148695 -1.8998501  -1.1953458 ]]]


 [[[-0.51308984 -1.3644258   1.0290838 ]
   [ 1.3716726   0.15442374  0.64232624]]

  [[ 0.93539244 -0.21348679 -0.53144366]
   [ 0.48807797  0.9623537   0.44795257]]]


 [[[ 0.04874428 -0.92287433 -1.8541312 ]
   [ 0.05049568  0.7397165  -1.5596782 ]]

  [[-0.07298505  0.18627425  0.8189418 ]
   [-0.19039515 -0.83063865 -0.28303656]]]], shape=(4, 2, 2, 3), dtype=float32)


In [320]:
dataset = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6,7,8,9])
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [322]:
dataset=dataset.repeat(3)
dataset

<RepeatDataset shapes: (), types: tf.int32>

In [315]:
x = tf.linspace(-8.,8,100) # 设置 x 坐标的间隔
y = tf.linspace(-8.,8,100) # 设置 y 坐标的间隔
x,y = tf.meshgrid(x,y) # 生成网格点，并拆分后返回 
z =tf.sqrt(x**2+y**2)
z=tf.sin(z)/z
z

<tf.Tensor: shape=(100, 100), dtype=float32, numpy=
array([[-0.08395312, -0.08742627, -0.08981076, ..., -0.08981076,
        -0.08742627, -0.08395312],
       [-0.08742627, -0.08984914, -0.09111905, ..., -0.09111906,
        -0.08984914, -0.08742627],
       [-0.08981076, -0.09111905, -0.09122175, ..., -0.09122175,
        -0.09111905, -0.08981076],
       ...,
       [-0.08981076, -0.09111906, -0.09122175, ..., -0.09122175,
        -0.09111906, -0.08981076],
       [-0.08742627, -0.08984914, -0.09111905, ..., -0.09111906,
        -0.08984914, -0.08742627],
       [-0.08395312, -0.08742627, -0.08981076, ..., -0.08981076,
        -0.08742627, -0.08395312]], dtype=float32)>

In [350]:
layer



<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.6590012 , 0.24243298, 0.09856589], dtype=float32)>